### ISSUE TITLE
While playing with the settings, the newly formatted code is copied to clipboard

### ISSUE THREAD

**Issue by SharmaAntriksh** [mogulargmbh/m-formatter#11]
**Description**
After formatting the code with my usual settings I try to see what else would make the code look better, for example I try to change the line width and try to hover between the range of 50 to 150 but the problem is after copying the code with Line Width of 150 if I change the Line Width to 50, the code with this formatting replaces the code in clipboard fromatted with 150 width setting

**Power Query- / M-Code**
```
let
    RandomDates = { #date ( 2021, 1, 1 ), #date ( 2018, 3, 6 ), #date ( 2022, 12, 30 ) },
    Source = List.Distinct ( RandomDates ),
    DateList =
        let
            MinDate       = List.Min ( Source ),
            MaxDate       = List.Max ( Source ),
            StartDate     = Number.From ( #date ( Date.Year ( MinDate ), 1, 1 ) ),
            EndDate       = Number.From ( #date ( Date.Year ( MaxDate ), 12, 31 ) ),
            Calendar      = { StartDate .. EndDate },
            ToTable       = Table.FromList ( Calendar, Splitter.SplitByNothing(), null, null, ExtraValues.Error ),
            ToDate        = Table.TransformColumnTypes ( ToTable, { "Column1", type date } ),
            ChangeColName = Table.RenameColumns ( ToDate, { { "Column1", "Date" } } )
        in
            ChangeColName,
    MonthName = Table.AddColumn ( DateList, "Month Name", each Date.MonthName ( [Date] ), type text ),
    MonthNumber = Table.AddColumn ( MonthName, "Month Number", each Date.Month ( [Date] ), Int64.Type ),
    CalendarYear = Table.AddColumn ( MonthNumber, "Calendar Year", each Date.Year ( [Date] ), Int64.Type ),
    DayName = Table.AddColumn ( CalendarYear, "Day of Week Name", each Date.DayOfWeekName ( [Date] ), type text ),
    DayNumber = Table.AddColumn ( DayName, "Day of Week Number", each Date.Day ( [Date] ), Int64.Type ),
    MonthShortName = Table.AddColumn ( DayNumber, "Month Initials", each Text.Start ( Date.MonthName ( [Date] ), 3 ), type text ),
    QuarterName = Table.AddColumn ( MonthShortName, "Quarter", each "Q" & Text.From ( Date.QuarterOfYear ( [Date] ) ), type text ),
    QuarterNumber = Table.AddColumn ( QuarterName, "Quarter Number", each Date.QuarterOfYear ( [Date] ), Int64.Type )
in
    QuarterNumber
```
![1](https://user-images.githubusercontent.com/73054674/120140715-c10f7d00-c1f8-11eb-9875-5fc889e3920f.gif)

**Expected behavior**
After changing settings the content of the clipboard shouldn't change.

Thank you again for creating this AWESOME formatter!

**Comment by UliPlabst** [comment]
Hi, thanks for filing an issue and for the appreciated feedback.  
Did you try to disable the "Auto copy to clipboard" option in **App-Options**? Disabling this feature will prevent the formatter to copy to clipboard after formatting happens. This will prevent your issue but will also mean that when you hit the formatting button you now need to manually click the copy code button. Let me know if this is a sufficient fix for your problem.  
I could also see that it would potentially make sense to change the "Auto copy to clipboard" option to an enumeration with 3 values:
- None: never copy to clipboard
- On click (default): copy only when the formatting happens because of a button click not because of the live preview feature
- Always: always copy to clipboard after formatting happens  
  
I could see people using any of the 3 values. Let me know what you think or if the simple boolean option as it is now is already sufficient for you.

**Comment by SharmaAntriksh** [comment]
Thanks for the instructions, I didn't realize there was an exisiting option, this solves my problem and I think the above 3 suggestions are good ones, what is available is now is already enough for me! Thanks!
